#!/bin/bash

#this check sound levels

SINK=$(if [[ $(pactl list short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,') = "" ]]; then
echo "1"
else
pactl list short | grep RUNNING | sed -e 's,^\([0-9][0-9]*\)[^0-9].*,\1,'
fi)

NOW=$( pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,' )

mute=$(pacmd list-sinks | awk '/muted/ { print $2 }' | head -n $(( $SINK + 1 )) | tail -n 1 | sed 's/muted://g; /^$/ d; s/\s*#.*//g')


if [ $mute = "yes" ]; then
  icon=""
  echo "$icon"
elif [ "$NOW" == "0" ]; then
	icon=""
  echo "$icon"
else
	icon=""
  echo "$icon $NOW%"
fi
